version: 2
jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2

    branches:
      only:
        - master

    steps:
      - checkout

      - run:
          name: Instalar cliente Docker
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Instalar Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Build container
          command: |
            set -x
            docker-compose -f docker-circle.yaml up --build -d

      - run:
          name: Espere container est√° pronto
          command: |
            set -x
            sleep 10

      - run:
          name: Monte GitHub Pages
          command: |
            set -x
            ./build.sh

      - run:
          name: Deploy GitHub Pages
          command: |
            set -x
            git clone -b gh-pages https://github.com/Guardians-DSC/docs.git /opt/gh-pages
            cp -rf ./_build/main/* /opt/gh-pages/
            cd /opt/gh-pages && git add .
            git -c user.name='CircleCI' -c user.email='travis' commit -m 'UPDATE GitHub Pages'
            git push

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
